// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_V-qecJ_KwFJygY2GP2yacWn7gA2UFt0',
    appId: '1:997061604237:web:a360386050be60218343c4',
    messagingSenderId: '997061604237',
    projectId: 'pick-me-61f34',
    authDomain: 'pick-me-61f34.firebaseapp.com',
    databaseURL: 'https://pick-me-61f34-default-rtdb.firebaseio.com',
    storageBucket: 'pick-me-61f34.appspot.com',
    measurementId: 'G-T962MERHYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdZ8IZ_5xCmBuIX5demh32yuO3fDhUy18',
    appId: '1:997061604237:android:a041174da7eb7d1b8343c4',
    messagingSenderId: '997061604237',
    projectId: 'pick-me-61f34',
    databaseURL: 'https://pick-me-61f34-default-rtdb.firebaseio.com',
    storageBucket: 'pick-me-61f34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi-Isv_MV7ju3WZy1N_4RaWtTzexvSLwU',
    appId: '1:997061604237:ios:f694f632d47ee8e08343c4',
    messagingSenderId: '997061604237',
    projectId: 'pick-me-61f34',
    databaseURL: 'https://pick-me-61f34-default-rtdb.firebaseio.com',
    storageBucket: 'pick-me-61f34.appspot.com',
    androidClientId: '997061604237-pul8invva2ceglj7qt8l723mo1gsiftk.apps.googleusercontent.com',
    iosClientId: '997061604237-slm0fqfjt3vrqcmeeee19n09tqdco9og.apps.googleusercontent.com',
    iosBundleId: 'mobile.flutter.pickme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi-Isv_MV7ju3WZy1N_4RaWtTzexvSLwU',
    appId: '1:997061604237:ios:f9dd198dc0c004168343c4',
    messagingSenderId: '997061604237',
    projectId: 'pick-me-61f34',
    databaseURL: 'https://pick-me-61f34-default-rtdb.firebaseio.com',
    storageBucket: 'pick-me-61f34.appspot.com',
    androidClientId: '997061604237-pul8invva2ceglj7qt8l723mo1gsiftk.apps.googleusercontent.com',
    iosClientId: '997061604237-mre0p2gbic4f7jc0gltkg59fp6je6s14.apps.googleusercontent.com',
    iosBundleId: 'mobile.flutter.pickme.RunnerTests',
  );
}
